---
title: "High-Dimensional Metrics"
author: "Victor Chernozhukov, Christian Hansen, Martin Spindler"
date: "`r Sys.Date()`"
output: rmarkdown::html_vignette
vignette: >
  %\VignetteIndexEntry{High-Dimensional Metrics}
  %\VignetteEngine{knitr::rmarkdown}
  %\VignetteEncoding{UTF-8}
---

# Overview

function | methods                              | comment                       | TBD
---------|--------------------------------------|-------------------------------|-------------------------------
rlasso   | summary, print, predict, model.matrix| default and formula interface |
rlogisticlasso |  summary, print, predict, model.matrix | default and forumla interface | rename: rlassologit
rlassoLM | print, summary, confint, plot | default and formula (TBD) interface | rename, polish plot, joint confint
rlassoIV | print, summary, confint | default interface | rename, formula interface
rlassoMany | print, summary, confint | default interface | rename, formula interface |
rlassoATE, rlassoLATE, rlassoATET, rlassoLATET | print, summary, confint | | |

To Do:

* rename functions
* choice of lambda
* joint CIs
* significance for logistic lasso
* wrap function for rlassoIV, rlassoMany, rlassoLM
* formula interface for rlassoIV, rlassoMany: design
* plots for all functions?
* further testing
* documentation and vignettes







