---
title: "High-Dimensional Metrics"
author: "Victor Chernozhukov, Christian Hansen, Martin Spindler"
date: "`r Sys.Date()`"
output: rmarkdown::html_vignette
vignette: >
  %\VignetteIndexEntry{High-Dimensional Metrics}
  %\VignetteEngine{knitr::rmarkdown}
  %\VignetteEncoding{UTF-8}
---

# Overview

# Example
```{r echo=FALSE}
library(hdm)
```

## rlasso

Generating data:
```{r}
set.seed(2)
n <- 100
p <- 20
px <- 5
X <- matrix(rnorm(n*p), ncol=p)
Xnew <- matrix(rnorm(n*p), ncol=p)
beta <- c(rep(2,px), rep(0,p-px))
y <- X %*% beta + rnorm(n)
```

rlasso

```{r}
l1 <- rlasso(X,y, intercept=TRUE, normalize=TRUE, post=TRUE ) # default interface
l2 <- rlasso(y~X) # formula interface
```

methods for rlasso

```{r}
print(l1)
summary(l1, all=FALSE) # show only coefficient which are not zero
head(predict(l1))
head(predict(l1, newdata=Xnew))
```


## rlogisticlasso
Generating data:
```{r}
set.seed(2)
n <- 100
p <- 20
px <- 5
X <- matrix(rnorm(n*p), ncol=p)
Xnew <- matrix(rnorm(n*p), ncol=p)
beta <- c(rep(2,px), rep(0,p-px))
ystar <-  X %*% beta + rnorm(n)
y <- as.integer(ystar >=0)
```

rlogisticlasso

```{r}
l3 <- rlassologit(X,y, intercept=TRUE, normalize=TRUE, post=TRUE ) # default interface
l4 <- rlassologit(y~X) # formula interface
```

methods for rlogisticlasso

```{r}
print(l3)
#summary(l3, all=FALSE) # show only coefficient which are not zero ########################################
head(predict(l3))
head(predict(l3, newdata=Xnew))
```

## rlassoLM

Generating data:
```{r}
set.seed(2)
n <- 100
p <- 20
px <- 5
X <- matrix(rnorm(n*p), ncol=p)
Xnew <- matrix(rnorm(n*p), ncol=p)
beta <- c(rep(2,px), rep(0,p-px))
y <- X %*% beta + rnorm(n)
```

rlassoEffect

```{r}
rLM <- rlassoEffect(X,y, index=c(1,2,9)) # I: selection of variables for inference
```

methods
```{r}
print(rLM)
summary(rLM)
confint(rLM)
```

```{r fig.width=5}
#plot(rLM, main="Estimated coefficients for selected variables")
```







